apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root_S&nh@"
        - name: MYSQL_DATABASE
          value: "product"
        - name: MYSQL_PASSWORD
          value: "S&cr&t&"
        - name: MYSQL_USER
          value: "u_product"
        - name: MYSQL_ROOT_HOST
          value: "%" 
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  selector:
    app: products
  ports:
    - port: 8080
      targetPort: 8080   
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:  
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080" 
        revision: "ef9d10ab1285f8851819f68833fae57cc1abc6fd"
        buildDate: "20230622130024"
       
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: host.k3d.internal:5000/products:latest
          ports: 
          - containerPort: 8080
          env: 
          - name: DB_USER
            value: 'u_product'
          - name: DB_PASS
            value: "S&cr&t&"  
          - name: DB_HOST
            value: "mysql"
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: "product"
